#baseURL: https://example.com/
title: Chernoff Faces 切尔诺夫的脸
theme: hugo-book
disablePathToLower: yes
enableGitInfo: yes

pygmentsUseClasses: false
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    tabWidth: 2
    style: "abap"
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    startLevel: 1

menu:
  #before:
  after:
    - name: Github
      url: https://github.com/MalteHueckstaedt
      weight: 20
    - name: Google Scholar
      url: https://scholar.google.com/citations?hl=en&user=EJTHqH4AAAAJ
      weight: 30
    - name: Research Gate
      url: https://www.researchgate.net/profile/Malte-Hueckstaedt
      weight: 40
    - name: LinkedIn
      url: https://de.linkedin.com/in/malte-hückstädt-82aa78208?challengeId=AQGlja9Bc2V4lwAAAYBREfppno4C2XhbbF-ybd8H-uKLrngqvYPqwuafiN5_is07oTZGDICckgI-AjB9OodDNPU__sOu1J3w1w&submissionId=317ce284-0835-e816-1de6-e15c28f47d4d
      weight: 50
    - name: Twitter
      url: https://twitter.com/Chernofffaces
      weight: 60
    - name: Instagramm
      url: https://twitter.com/Chernofffaces
      weight: 70

params:
  # BookMenuBundle: /menu
  BookComments: yes
  BookDateFormat: January 2, 2006
  BookEditPath: /blob/master
  BookPortableLinks: yes
  BookRepo: https://github.com/MalteHueckstaedt/blogdown_chernoff_faces
  BookSearch: yes
  BookSection: docs
  BookServiceWorker: yes
  BookTheme: light
  BookToC: yes
  BookTranslatedOnly: no
highlight:
    codeFences: false
